version: '3'
services:
  cache:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    ports:
      - "5432:5432"
  erp:
    build: .
    command: bee run
    volumes:
      - .:/go/src/projectERP
    ports:
      - "8888:8888"
    depends_on:
      - db
      - cache