version: '3'
services:
  cache:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: IYfdxRuiT76F4j5
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  erp:
    build: .
    command: bee run
    volumes:
      - .:/go/src/projectERP
    ports:
      - "8888:8888"
    depends_on:
      - db
      - cache